version: '3.1'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: data
    ports:
      - 5432:5432